# site title
title: Breathiness

# user name or organization name
user: breathiness

# issue repository
repository: breathiness.github.io

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 9#1cff6bb078bb79017f9b9f0cdd63454a06bb957

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
